import { Geist, Geist_Mono, Poppins, Bitter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/components/theme-provider";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], 
});

export const metadata = {
  title: "Gubuk Kopi App",
  description: "Generated by create next app",
   icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className="scroll-smooth">
        <head>
        {/* CSS Summernote */}
        <link
          href="https://cdn.jsdelivr.net/npm/summernote@0.8.20/dist/summernote-lite.min.css"
          rel="stylesheet"
        />
          <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
        {/* jQuery (dibutuhkan Summernote) */}
        <script
          src="https://code.jquery.com/jquery-3.7.1.min.js"
          defer
        ></script>
      </head>
      <body className={poppins.className}>
        {/* Header */}
        {/* <Header /> */}
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        {/* <Footer /> */}
         <Script
          src="https://cdn.jsdelivr.net/npm/summernote@0.8.20/dist/summernote-lite.min.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
